### ISSUE TITLE
Double-$ in titles

### ISSUE THREAD

**Issue by Tokaleto** [notabugio/notabug#10]
The second $ in the title of https://notabug.io/t/videos/comments/4e49fcb07adc30625e28bac6ec61ef95aabb6b02/thoughts-did-mama-go-overboard-with-this-a-whoopin-or-nah is displayed at the beginning, but then vanishes. Reddit (in the old design) doesn't do that: https://old.reddit.com/r/TransyTalk/comments/8zzasn/testtzudfgh/ . It may have done that in the past, but I this happens obviously via JavaScript and notabug.io makes probably much more use of it, I think it was introduced by notabug.io.

**Comment by go1dfish** [comment]
I think this might be a more underlying issue with either GUN or redis.

I've seen that post throw validation errors so this is a bit deeper than a display issue, the second dollar sign seems to be getting lost.

Is this consistently happening with $$'s in titles or other fields?

**Comment by go1dfish** [comment]
Data looks right in redis, and server rendering works properly; this is an issue with either gun or gun-flint

**Comment by go1dfish** [comment]
I think this is fixed on notabug.io as of 0.7.6  Closing this, let me know if you see it again.
