### ISSUE TITLE
Error running /.start.sh

### ISSUE THREAD

**Issue by 12buntu** [notabugio/notabug#11]
`Hello wonderful person! :) Thanks for using GUN, feel free to ask for help on https://gitter.im/amark/gun and ask StackOverflow questions tagged with 'gun'!
start :)
>>>>>>>>> { gun: Gun { _: [Circular] },
  '$': Gun { _: [Circular] },
  opt:
   { peers: { 'http://notabug.io/gun': [Object] },
     localStorage: false,
     until: [ 1000 ],
     super: true,
     web:
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        _connections: 0,
        _handle: null,
        _usingWorkers: false,
        _workers: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        keepAliveTimeout: 5000,
        _pendingResponseData: 0,
        maxHeadersCount: null,
        [Symbol(IncomingMessage)]: [Function],
        [Symbol(ServerResponse)]: [Function],
        [Symbol(asyncId)]: -1 },
     radisk: false,
     WebSocket:
      { [Function: WebSocket]
        CONNECTING: 0,
        OPEN: 1,
        CLOSING: 2,
        CLOSED: 3,
        Server: [Function: WebSocketServer],
        Receiver: [Function: Receiver],
        Sender: [Function: Sender] } },
  root: [Circular],
  graph: {},
  on:
   { [Function: onto]
     put: [Function],
     get: [Function],
     _: { next: [Function: next] },
     off: [Function] },
  ask: [Function: ask],
  dup: { s: {}, check: [Function], track: [Function] },
  tag: { in: { tag: 'in', to: [Object], last: [Object] } } }
WARNING: `lib/bye` is out of date!
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1162:14)
Emitted 'error' event at:
    at ExpressRedisCache.<anonymous> (/notabug/node_modules/express-redis-cache/lib/ExpressRedisCache.js:85:14)
    at RedisClient.emit (events.js:182:13)
    at RedisClient.EventEmitter.emit (domain.js:442:20)
    at RedisClient.on_error (/notabug/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/notabug/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error: Forever detected script exited with code: 1
error: Script restart attempt #447
`

I'm not sure what I'm doing wrong here, can somebody help?

**Comment by go1dfish** [comment]
Been moving pretty fast lately and haven't updated documentation.  Redis is currently required for endpoint cacheing, but I want to try to keep redis optional.

Once I'm done with such rapid change I'll make a call for more peers/upgrades but for now just keep poking me if you run into problems and that will help me to update the docs as well.

Highly recommend running --redis instead of --persist now, runs much faster.
