### ISSUE TITLE
Possible issues starting dev docker?

### ISSUE THREAD

**Issue by jondkelley** [notabugio/notabug#16]
Phenomenal work here.

I'm a bit wondering how to start local dev?

I ran start.sh with a local redis running on my parent OS. I get "empty reply from server" from port 3001 while the start.sh has started in foreground.

I just see the following (snippert below), what should I change the peer configs for to get a local development instance? Trying to familiarize with the architecture and possibly contribute.

It seems to start.
```
44.8 MB rss. 18.2 MB hT. 12.4 MB hU. 1 peers. 0 nodes.
44.8 MB rss. 18.2 MB hT. 12.4 MB hU. 1 peers. 0 nodes.
44.8 MB rss. 18.2 MB hT. 12.4 MB hU. 1 peers. 0 nodes.
44.8 MB rss. 18.2 MB hT. 12.4 MB hU. 1 peers. 0 nodes.
44.8 MB rss. 18.2 MB hT. 12.4 MB hU. 1 peers. 0 nodes.
44.8 MB rss. 18.2 MB hT. 12.4 MB hU. 1 peers. 0 nodes.
44.8 MB rss. 18.2 MB hT. 12.4 MB hU. 1 peers. 0 nodes.
44.8 MB rss. 18.2 MB hT. 12.4 MB hU. 1 peers. 0 nodes.

```

**Comment by jondkelley** [comment]
This worked

```
git clone https://github.com/notabugio/notabug.git
cd notabug && yarn && yarn build
cp -R build htdocs
node server.js --persist --debug --evict --peer https://notabug.io/gun --port 3001
```

The web interface shows Cannot GET / at this point though.

**Comment by go1dfish** [comment]
Try:
    
    node server.js --persist --debug --evict --render --peer  https://notabug.io/gun --port 3001

**Comment by go1dfish** [comment]
Also should be noted I don't use the docker setup myself and haven't messed with it much.

I use forever to manage processes on notabug.io with this config:

https://github.com/notabugio/notabug/blob/master/peer-configs/notabugio.json

And put nginx in front of that to bring /gun to port 3333 and everything else to 4444

Just the http peer there should be enough (when peered to notabug.io) to get the site running using notabug.io as an indexer.

**Comment by go1dfish** [comment]
Closing this since the docker setup is no long present after I did the move to parcel, but I may add some docker configs soon for easier setup as I've been using it more myself on other projects.
