### ISSUE TITLE
New Submission Does Not Show

### ISSUE THREAD

**Issue by rawburt** [notabugio/notabug#3]
A new submission does not show on the Topic listing. Once it has a vote it _does_ show. Is this expected behavior? Why?

**Comment by rawburt** [comment]
Also -- is there an IRC chan or some specific location to ask questions without using GitHub?

**Comment by go1dfish** [comment]
You could just post to notabug, either in the notabug topic or suggestions; I'd likely see it sooner there than here.  After logins I plan to add chat functionality now that the site is running smoother.

Yes it is currently a feature that new submissions without a vote do not show in the hot listing, this is a measure to discourage spam.  If you can you should upvote your own submissions for visibility.

This score threshold is currently hardcoded at 1, but you can adjust it with urls like:

https://notabug.io/?&threshold=-1

This will eventually be made a user preference in the UI.


Proof of Work was originally conceived as a spam prevention measure:

https://en.wikipedia.org/wiki/Proof-of-work_system

Notabug uses it for exactly that, but for right now it is only used for voting; an alternative approach could be to require proof of work for submissions at all but I think that might discourage participation.
